/*@type {import('tailwindcss').Config} */
export default {
  content: [  "./app/**/*.{js,jsx}",
  "./components/**/*.{js,jsx}",],
  theme: {
    extend: {
      colors: {
        primary: "#00458b",
        secondary: "#356a32",
        background: "#f4fbfd",
        surface: "#f4fbfd",
        "surface-bright": "#f4fbfd",
        "surface-container-low": "#eef5f7",
        "surface-container": "#e8eff1",
        "surface-container-high": "#e2e9eb",
        "surface-container-highest": "#dde4e6",
        "surface-container-lowest": "#ffffff",
        "surface-variant": "#dde4e6",
        "on-surface": "#161d1e",
        "on-surface-variant": "#424751",
        "on-primary": "#ffffff",
        "on-primary-fixed": "#001b3d",
        "on-primary-fixed-variant": "#00468c",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#3b7037",
        "primary-container": "#235da9",
        "primary-fixed": "#d6e3ff",
        "primary-fixed-dim": "#a9c7ff",
        "secondary-container": "#b6f2ab",
        "secondary-fixed": "#b6f2ab",
        "secondary-fixed-dim": "#9bd591",
        outline: "#737782",
        "outline-variant": "#c2c6d3",
        ink: {
          900: "#0d203b",
          800: "#1a3050",
          700: "#243d63",
        },
        forest: {
          700: "#2a5427",
          600: "#356a32",
          500: "#4a7a44",
        },
        clay: {
          600: "#7a6a5a",
        },
        accent: {
          600: "#245eaa",
          500: "#2f72c8",
        },
      },
      fontFamily: {
        headline: ["Newsreader", "serif"],
        body: ["Work Sans", "sans-serif"],
        label: ["Work Sans", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        "2xl": "1rem",
        full: "0.75rem",
      },
      boxShadow: {
        soft: "0 2px 20px rgba(13, 32, 59, 0.08)",
      },
    },
  },
  plugins: [],
};
